// +build !ignore_autogenerated

/*
Copyright (c) 2016-2017 Intel Corporation.

Redistribution.  Redistribution and use in binary form, without
modification, are permitted provided that the following conditions are
met:
  Redistributions must reproduce the above copyright notice and the
  following disclaimer in the documentation and/or other materials
  provided with the distribution.
  Neither the name of Intel Corporation nor the names of its suppliers
  may be used to endorse or promote products derived from this software
  without specific prior written permission.
  No reverse engineering, decompilation, or disassembly of this software
  is permitted.

Limited patent license.  Intel Corporation grants a world-wide,
royalty-free, non-exclusive license under patents it now or hereafter
owns or controls to make, have made, use, import, offer to sell and
sell ("Utilize") this software, but solely to the extent that any
such patent is necessary to Utilize the software alone, or in
combination with an operating system licensed under an approved Open
Source license as listed by the Open Source Initiative at
http://opensource.org/licenses.  The patent license shall not apply to
any other combinations which include this software.  No hardware per
se is licensed hereunder.

DISCLAIMER.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	helium "github.com/nervanasystems/nuas/pkg/apis/helium"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_Batch_To_helium_Batch,
		Convert_helium_Batch_To_v1_Batch,
		Convert_v1_BatchList_To_helium_BatchList,
		Convert_helium_BatchList_To_v1_BatchList,
		Convert_v1_Interact_To_helium_Interact,
		Convert_helium_Interact_To_v1_Interact,
		Convert_v1_InteractList_To_helium_InteractList,
		Convert_helium_InteractList_To_v1_InteractList,
		Convert_v1_Jobtype_To_helium_Jobtype,
		Convert_helium_Jobtype_To_v1_Jobtype,
		Convert_v1_JobtypeList_To_helium_JobtypeList,
		Convert_helium_JobtypeList_To_v1_JobtypeList,
		Convert_v1_JobtypeSpec_To_helium_JobtypeSpec,
		Convert_helium_JobtypeSpec_To_v1_JobtypeSpec,
		Convert_v1_JobtypeStatus_To_helium_JobtypeStatus,
		Convert_helium_JobtypeStatus_To_v1_JobtypeStatus,
		Convert_v1_JobtypeStatusStrategy_To_helium_JobtypeStatusStrategy,
		Convert_helium_JobtypeStatusStrategy_To_v1_JobtypeStatusStrategy,
		Convert_v1_JobtypeStrategy_To_helium_JobtypeStrategy,
		Convert_helium_JobtypeStrategy_To_v1_JobtypeStrategy,
		Convert_v1_Streaming_To_helium_Streaming,
		Convert_helium_Streaming_To_v1_Streaming,
		Convert_v1_StreamingList_To_helium_StreamingList,
		Convert_helium_StreamingList_To_v1_StreamingList,
		Convert_v1_Training_To_helium_Training,
		Convert_helium_Training_To_v1_Training,
		Convert_v1_TrainingList_To_helium_TrainingList,
		Convert_helium_TrainingList_To_v1_TrainingList,
	)
}

func autoConvert_v1_Batch_To_helium_Batch(in *Batch, out *helium.Batch, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1_Batch_To_helium_Batch is an autogenerated conversion function.
func Convert_v1_Batch_To_helium_Batch(in *Batch, out *helium.Batch, s conversion.Scope) error {
	return autoConvert_v1_Batch_To_helium_Batch(in, out, s)
}

func autoConvert_helium_Batch_To_v1_Batch(in *helium.Batch, out *Batch, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_helium_Batch_To_v1_Batch is an autogenerated conversion function.
func Convert_helium_Batch_To_v1_Batch(in *helium.Batch, out *Batch, s conversion.Scope) error {
	return autoConvert_helium_Batch_To_v1_Batch(in, out, s)
}

func autoConvert_v1_BatchList_To_helium_BatchList(in *BatchList, out *helium.BatchList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helium.Batch)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_BatchList_To_helium_BatchList is an autogenerated conversion function.
func Convert_v1_BatchList_To_helium_BatchList(in *BatchList, out *helium.BatchList, s conversion.Scope) error {
	return autoConvert_v1_BatchList_To_helium_BatchList(in, out, s)
}

func autoConvert_helium_BatchList_To_v1_BatchList(in *helium.BatchList, out *BatchList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Batch, 0)
	} else {
		out.Items = *(*[]Batch)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_helium_BatchList_To_v1_BatchList is an autogenerated conversion function.
func Convert_helium_BatchList_To_v1_BatchList(in *helium.BatchList, out *BatchList, s conversion.Scope) error {
	return autoConvert_helium_BatchList_To_v1_BatchList(in, out, s)
}

func autoConvert_v1_Interact_To_helium_Interact(in *Interact, out *helium.Interact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1_Interact_To_helium_Interact is an autogenerated conversion function.
func Convert_v1_Interact_To_helium_Interact(in *Interact, out *helium.Interact, s conversion.Scope) error {
	return autoConvert_v1_Interact_To_helium_Interact(in, out, s)
}

func autoConvert_helium_Interact_To_v1_Interact(in *helium.Interact, out *Interact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_helium_Interact_To_v1_Interact is an autogenerated conversion function.
func Convert_helium_Interact_To_v1_Interact(in *helium.Interact, out *Interact, s conversion.Scope) error {
	return autoConvert_helium_Interact_To_v1_Interact(in, out, s)
}

func autoConvert_v1_InteractList_To_helium_InteractList(in *InteractList, out *helium.InteractList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helium.Interact)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_InteractList_To_helium_InteractList is an autogenerated conversion function.
func Convert_v1_InteractList_To_helium_InteractList(in *InteractList, out *helium.InteractList, s conversion.Scope) error {
	return autoConvert_v1_InteractList_To_helium_InteractList(in, out, s)
}

func autoConvert_helium_InteractList_To_v1_InteractList(in *helium.InteractList, out *InteractList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Interact, 0)
	} else {
		out.Items = *(*[]Interact)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_helium_InteractList_To_v1_InteractList is an autogenerated conversion function.
func Convert_helium_InteractList_To_v1_InteractList(in *helium.InteractList, out *InteractList, s conversion.Scope) error {
	return autoConvert_helium_InteractList_To_v1_InteractList(in, out, s)
}

func autoConvert_v1_Jobtype_To_helium_Jobtype(in *Jobtype, out *helium.Jobtype, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_JobtypeSpec_To_helium_JobtypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_JobtypeStatus_To_helium_JobtypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Jobtype_To_helium_Jobtype is an autogenerated conversion function.
func Convert_v1_Jobtype_To_helium_Jobtype(in *Jobtype, out *helium.Jobtype, s conversion.Scope) error {
	return autoConvert_v1_Jobtype_To_helium_Jobtype(in, out, s)
}

func autoConvert_helium_Jobtype_To_v1_Jobtype(in *helium.Jobtype, out *Jobtype, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_helium_JobtypeSpec_To_v1_JobtypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_helium_JobtypeStatus_To_v1_JobtypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_helium_Jobtype_To_v1_Jobtype is an autogenerated conversion function.
func Convert_helium_Jobtype_To_v1_Jobtype(in *helium.Jobtype, out *Jobtype, s conversion.Scope) error {
	return autoConvert_helium_Jobtype_To_v1_Jobtype(in, out, s)
}

func autoConvert_v1_JobtypeList_To_helium_JobtypeList(in *JobtypeList, out *helium.JobtypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helium.Jobtype)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_JobtypeList_To_helium_JobtypeList is an autogenerated conversion function.
func Convert_v1_JobtypeList_To_helium_JobtypeList(in *JobtypeList, out *helium.JobtypeList, s conversion.Scope) error {
	return autoConvert_v1_JobtypeList_To_helium_JobtypeList(in, out, s)
}

func autoConvert_helium_JobtypeList_To_v1_JobtypeList(in *helium.JobtypeList, out *JobtypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Jobtype, 0)
	} else {
		out.Items = *(*[]Jobtype)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_helium_JobtypeList_To_v1_JobtypeList is an autogenerated conversion function.
func Convert_helium_JobtypeList_To_v1_JobtypeList(in *helium.JobtypeList, out *JobtypeList, s conversion.Scope) error {
	return autoConvert_helium_JobtypeList_To_v1_JobtypeList(in, out, s)
}

func autoConvert_v1_JobtypeSpec_To_helium_JobtypeSpec(in *JobtypeSpec, out *helium.JobtypeSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_JobtypeSpec_To_helium_JobtypeSpec is an autogenerated conversion function.
func Convert_v1_JobtypeSpec_To_helium_JobtypeSpec(in *JobtypeSpec, out *helium.JobtypeSpec, s conversion.Scope) error {
	return autoConvert_v1_JobtypeSpec_To_helium_JobtypeSpec(in, out, s)
}

func autoConvert_helium_JobtypeSpec_To_v1_JobtypeSpec(in *helium.JobtypeSpec, out *JobtypeSpec, s conversion.Scope) error {
	return nil
}

// Convert_helium_JobtypeSpec_To_v1_JobtypeSpec is an autogenerated conversion function.
func Convert_helium_JobtypeSpec_To_v1_JobtypeSpec(in *helium.JobtypeSpec, out *JobtypeSpec, s conversion.Scope) error {
	return autoConvert_helium_JobtypeSpec_To_v1_JobtypeSpec(in, out, s)
}

func autoConvert_v1_JobtypeStatus_To_helium_JobtypeStatus(in *JobtypeStatus, out *helium.JobtypeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_JobtypeStatus_To_helium_JobtypeStatus is an autogenerated conversion function.
func Convert_v1_JobtypeStatus_To_helium_JobtypeStatus(in *JobtypeStatus, out *helium.JobtypeStatus, s conversion.Scope) error {
	return autoConvert_v1_JobtypeStatus_To_helium_JobtypeStatus(in, out, s)
}

func autoConvert_helium_JobtypeStatus_To_v1_JobtypeStatus(in *helium.JobtypeStatus, out *JobtypeStatus, s conversion.Scope) error {
	return nil
}

// Convert_helium_JobtypeStatus_To_v1_JobtypeStatus is an autogenerated conversion function.
func Convert_helium_JobtypeStatus_To_v1_JobtypeStatus(in *helium.JobtypeStatus, out *JobtypeStatus, s conversion.Scope) error {
	return autoConvert_helium_JobtypeStatus_To_v1_JobtypeStatus(in, out, s)
}

func autoConvert_v1_JobtypeStatusStrategy_To_helium_JobtypeStatusStrategy(in *JobtypeStatusStrategy, out *helium.JobtypeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_JobtypeStatusStrategy_To_helium_JobtypeStatusStrategy is an autogenerated conversion function.
func Convert_v1_JobtypeStatusStrategy_To_helium_JobtypeStatusStrategy(in *JobtypeStatusStrategy, out *helium.JobtypeStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_JobtypeStatusStrategy_To_helium_JobtypeStatusStrategy(in, out, s)
}

func autoConvert_helium_JobtypeStatusStrategy_To_v1_JobtypeStatusStrategy(in *helium.JobtypeStatusStrategy, out *JobtypeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_helium_JobtypeStatusStrategy_To_v1_JobtypeStatusStrategy is an autogenerated conversion function.
func Convert_helium_JobtypeStatusStrategy_To_v1_JobtypeStatusStrategy(in *helium.JobtypeStatusStrategy, out *JobtypeStatusStrategy, s conversion.Scope) error {
	return autoConvert_helium_JobtypeStatusStrategy_To_v1_JobtypeStatusStrategy(in, out, s)
}

func autoConvert_v1_JobtypeStrategy_To_helium_JobtypeStrategy(in *JobtypeStrategy, out *helium.JobtypeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_JobtypeStrategy_To_helium_JobtypeStrategy is an autogenerated conversion function.
func Convert_v1_JobtypeStrategy_To_helium_JobtypeStrategy(in *JobtypeStrategy, out *helium.JobtypeStrategy, s conversion.Scope) error {
	return autoConvert_v1_JobtypeStrategy_To_helium_JobtypeStrategy(in, out, s)
}

func autoConvert_helium_JobtypeStrategy_To_v1_JobtypeStrategy(in *helium.JobtypeStrategy, out *JobtypeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_helium_JobtypeStrategy_To_v1_JobtypeStrategy is an autogenerated conversion function.
func Convert_helium_JobtypeStrategy_To_v1_JobtypeStrategy(in *helium.JobtypeStrategy, out *JobtypeStrategy, s conversion.Scope) error {
	return autoConvert_helium_JobtypeStrategy_To_v1_JobtypeStrategy(in, out, s)
}

func autoConvert_v1_Streaming_To_helium_Streaming(in *Streaming, out *helium.Streaming, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1_Streaming_To_helium_Streaming is an autogenerated conversion function.
func Convert_v1_Streaming_To_helium_Streaming(in *Streaming, out *helium.Streaming, s conversion.Scope) error {
	return autoConvert_v1_Streaming_To_helium_Streaming(in, out, s)
}

func autoConvert_helium_Streaming_To_v1_Streaming(in *helium.Streaming, out *Streaming, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_helium_Streaming_To_v1_Streaming is an autogenerated conversion function.
func Convert_helium_Streaming_To_v1_Streaming(in *helium.Streaming, out *Streaming, s conversion.Scope) error {
	return autoConvert_helium_Streaming_To_v1_Streaming(in, out, s)
}

func autoConvert_v1_StreamingList_To_helium_StreamingList(in *StreamingList, out *helium.StreamingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helium.Streaming)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_StreamingList_To_helium_StreamingList is an autogenerated conversion function.
func Convert_v1_StreamingList_To_helium_StreamingList(in *StreamingList, out *helium.StreamingList, s conversion.Scope) error {
	return autoConvert_v1_StreamingList_To_helium_StreamingList(in, out, s)
}

func autoConvert_helium_StreamingList_To_v1_StreamingList(in *helium.StreamingList, out *StreamingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Streaming, 0)
	} else {
		out.Items = *(*[]Streaming)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_helium_StreamingList_To_v1_StreamingList is an autogenerated conversion function.
func Convert_helium_StreamingList_To_v1_StreamingList(in *helium.StreamingList, out *StreamingList, s conversion.Scope) error {
	return autoConvert_helium_StreamingList_To_v1_StreamingList(in, out, s)
}

func autoConvert_v1_Training_To_helium_Training(in *Training, out *helium.Training, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1_Training_To_helium_Training is an autogenerated conversion function.
func Convert_v1_Training_To_helium_Training(in *Training, out *helium.Training, s conversion.Scope) error {
	return autoConvert_v1_Training_To_helium_Training(in, out, s)
}

func autoConvert_helium_Training_To_v1_Training(in *helium.Training, out *Training, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_helium_Training_To_v1_Training is an autogenerated conversion function.
func Convert_helium_Training_To_v1_Training(in *helium.Training, out *Training, s conversion.Scope) error {
	return autoConvert_helium_Training_To_v1_Training(in, out, s)
}

func autoConvert_v1_TrainingList_To_helium_TrainingList(in *TrainingList, out *helium.TrainingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helium.Training)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_TrainingList_To_helium_TrainingList is an autogenerated conversion function.
func Convert_v1_TrainingList_To_helium_TrainingList(in *TrainingList, out *helium.TrainingList, s conversion.Scope) error {
	return autoConvert_v1_TrainingList_To_helium_TrainingList(in, out, s)
}

func autoConvert_helium_TrainingList_To_v1_TrainingList(in *helium.TrainingList, out *TrainingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Training, 0)
	} else {
		out.Items = *(*[]Training)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_helium_TrainingList_To_v1_TrainingList is an autogenerated conversion function.
func Convert_helium_TrainingList_To_v1_TrainingList(in *helium.TrainingList, out *TrainingList, s conversion.Scope) error {
	return autoConvert_helium_TrainingList_To_v1_TrainingList(in, out, s)
}
