/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1

import (
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"github.com/nervanasystems/nuas/pkg/apis/helium"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	heliumJobtypeStorage = builders.NewApiResource( // Resource status endpoint
		helium.InternalJobtype,
		JobtypeSchemeFns{},
		func() runtime.Object { return &Jobtype{} },     // Register versioned resource
		func() runtime.Object { return &JobtypeList{} }, // Register versioned resource list
		&JobtypeStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("helium.aipg.intel.com", "v1").WithResources(
		heliumJobtypeStorage,
		builders.NewApiResource( // Resource status endpoint
			helium.InternalJobtypeStatus,
			JobtypeSchemeFns{},
			func() runtime.Object { return &Jobtype{} },     // Register versioned resource
			func() runtime.Object { return &JobtypeList{} }, // Register versioned resource list
			&JobtypeStatusStrategy{builders.StatusStorageStrategySingleton},
		), builders.NewApiResourceWithStorage(
			helium.InternalBatchJobtypeREST,
			builders.SchemeFnsSingleton,
			func() runtime.Object { return &Batch{} }, // Register versioned resource
			nil,
			func() rest.Storage { return &BatchJobtypeREST{helium.NewJobtypeRegistry(heliumJobtypeStorage)} },
		),
		builders.NewApiResourceWithStorage(
			helium.InternalInteractJobtypeREST,
			builders.SchemeFnsSingleton,
			func() runtime.Object { return &Interact{} }, // Register versioned resource
			nil,
			func() rest.Storage { return &InteractJobtypeREST{helium.NewJobtypeRegistry(heliumJobtypeStorage)} },
		),
		builders.NewApiResourceWithStorage(
			helium.InternalStreamingJobtypeREST,
			builders.SchemeFnsSingleton,
			func() runtime.Object { return &Streaming{} }, // Register versioned resource
			nil,
			func() rest.Storage { return &StreamingJobtypeREST{helium.NewJobtypeRegistry(heliumJobtypeStorage)} },
		),
		builders.NewApiResourceWithStorage(
			helium.InternalTrainingJobtypeREST,
			builders.SchemeFnsSingleton,
			func() runtime.Object { return &Training{} }, // Register versioned resource
			nil,
			func() rest.Storage { return &TrainingJobtypeREST{helium.NewJobtypeRegistry(heliumJobtypeStorage)} },
		),
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// Jobtype Functions and Structs
//
// +k8s:deepcopy-gen=false
type JobtypeSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type JobtypeStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type JobtypeStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type JobtypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Jobtype `json:"items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type BatchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Batch `json:"items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type InteractList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Interact `json:"items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type StreamingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Streaming `json:"items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type TrainingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Training `json:"items"`
}
